{
  "hash": "a021f104329757d893e889e06bfe2bb3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"How to use the World Inequality Database (WID)?\"\nsubtitle: \"Accessing and utilizing data of the WID.world database.\"\ndescription: \"\"\nauthor: \"Peter Baumgartner\"\ndate: \"2024-07-27\"\nimage: \"WID-Logo-min.png\"\nimage-alt: \"Logo of the World Inequality Lab\"\ncategories: [inequality, research, WID, open-data]\ndate-modified: \"2024-07-27\"\ndraft: false\nbibliography: references.bib\n---\n\n\n\n\n\n![Logo of the [World Inequality Lab](https://inequalitylab.world/)\n(Screenshot). The WIL is a global research center studying inequality\nand public policies promoting social, economic, and environmental\njustice.](WID-Logo-min.png)\n\n## Research on Social Inequality\n\nI plan to write blog articles about social inequality in Austria, my\nnative country. To be innovative, I want to avoid repeating what other\npeople (journalists, scientists) were saying (claiming) but to\nillustrate my thinking backed by original data. But where does the data\ncome from?\n\n### Some Data Resources for Inequality Research\n\n::: my-resource\n::: my-resource-header\n::: {#lem-inequality-data}\n: Some Data Resources for Inequality Research\n:::\n:::\n\n::: my-resource-container\n-   **WID**: The [World Inequality\n    Database](https://wid.world/wid-world/) (WID) aims to provide open\n    and convenient access to the most extensive available database on\n    the historical evolution of the world distribution of income and\n    wealth, both within countries and between countries\n    [@worldinequalitylab2024].\n-   **OWID**: [Our World In Data](https://ourworldindata.org/) (OWID) is\n    an online publication that focuses on large global problems such as\n    poverty, disease, hunger, climate change, war, existential risks,\n    and inequality [@globalchangedatalab2024].\n-   **PIP**: The [Poverty and Inequality\n    Platform](https://pip.worldbank.org/home) (PIP) is an interactive\n    computational tool that offers users quick access to the World\n    Bank's estimates of poverty, inequality, and shared prosperity. PIP\n    provides a comprehensive view of global, regional, and country-level\n    trends for more than 160 economies around the World\n    [@worldbank2024].\n-   **LIS**: The [Luxembourg Income Study\n    Database](https://www.lisdatacenter.org/) (LIS) is a data archive\n    and research center dedicated to cross-national analysis. It is home\n    to the [Luxembourg Income Study\n    Database](http://www.lisdatacenter.org/our-data/lis-database/) (LIS)\n    and the [Luxembourg Wealth Study\n    Database](http://www.lisdatacenter.org/our-data/lws-database/) (LWS)\n    [@lisauthorcollective2024].\n:::\n:::\n\n### WID & A Brief History of Equality\n\nUnderstanding the use of all these data resources is a complex\nenterprise. As a starting point, I will concentrate on the World\nInequality Database (<a class='glossary' title='The ‘World Inequality Database’ (WID) aims to provide open and convenient access to the most extensive available database on the historical evolution of the world distribution of income and wealth, both within countries and between countries. WID.WORLD'>WID</a>) because there exist several\nmonographs where these data are used and interpreted.\n\nAs a first step, I am going to follow the arguments of one book that I\nwill use as <a class='glossary' title='Advance organizers are pedagogic devices that bridge the gap between what learners already know and what learners need to know. (Encyclopedia of the Science of Learning)'>advanced organizer</a>. I am referring to \"A\nBrief History of Equality\" (BHE), which is only 274 pages, is a kind of\nexecutive summary of previous books by Thomas Piketty: \"Capital in the\nTwenty-First Century\" (816 pages) and \"Capital and Ideology\" (1093\npages) [@piketty2020a; @piketty2017].\n\n### Lacking Graphs about Austria\n\nMost of the time, BHE uses global, regional, or data from big,\nrespectively 'important' countries like China, France, Germany, India,\nUnited Kingdom, United States, etc. Data on Austria and its\ninterpretation are missing from the mentioned book and most scientific\npublications [referenced on the\nwebsite](https://wid.world/methodology/#library-browse-by-country). An\nexception is the working paper \"Distributional National Accounts (DINA)\"\nfor Austria, 2004-2016 by @jestl2020. But this paper partly uses\ndifferent indices and different concepts (for instance, the [Gini\ncoefficient](https://ourworldindata.org/what-is-the-gini-coefficient)).\n\nOn the <a class='glossary' title='The ‘World Inequality Database’ (WID) aims to provide open and convenient access to the most extensive available database on the historical evolution of the world distribution of income and wealth, both within countries and between countries. WID.WORLD'>WID</a> website there are two other articles where at\nleast Austria is shown in some graphs: You will find five figures with\nAustria data in \"What's New About Income Inequality in Europe\n(1980-2019)?\" by @morgan2020 and other two figures in \"How Unequal Is\nEurope? Evidence from Distributional National Accounts, 1980-2017\" by\n@blanchet2019.\n\nSo, creating figures with Austrian data is not only an excellent\nexercise but the result could also increase our knowledge about the\nmechanisms and patterns of social inequality.\n\n## Using the WID website\n\n### Key resources\n\nTo get started effectively, one has to overcome a paradoxical situation:\nThe more detailed the methodological guidelines, the more difficult it\nis to find an appropriate entry point to get started.\n\n::: my-resource\n::: my-resource-header\n::: {#lem-inequality-methodology}\n: Methodological Guidelines & Other Resources\n:::\n:::\n\n::: my-resource-container\n-   [Distributional National Accounts (DINA)\n    Guidelines](https://wid.world/document/distributional-national-accounts-guidelines-2020-concepts-and-methods-used-in-the-world-inequality-database/):\n    This is the central resource for understanding the methodology\n    behind the decomposition of <a class='glossary' title='National accounts are a system of accounts and balance sheets that provide a broad and integrated framework to describe an economy, whether a region, a country, or a group of countries such as the European Union (EU). For internationally comparable national accounts this system needs to be based on common concepts, definitions, classifications and accounting rules, in order to arrive at a consistent, reliable and comparable quantitative description of an economy. National accounts provide systematic and detailed economic data useful for economic analysis to support the development and monitoring of policy-making. eurostat - Statistics explained.'>national accounts</a> and\n    the inequality series for income and wealth. The purpose of these\n    Distributional National Accounts (<a class='glossary' title='Distributional national accounts (DINAs) aim to gather information on the distribution of the net national income and to explore it over time. (Distributional National Accounts (DINA) for Austria, 2004-2016)'>DINA</a>) guidelines\n    is to present the concepts, data sources, and methods used in the\n    World Inequality Database (<a class='glossary' title='The ‘World Inequality Database’ (WID) aims to provide open and convenient access to the most extensive available database on the historical evolution of the world distribution of income and wealth, both within countries and between countries. WID.WORLD'>WID</a>). It is a long\n    document with 186 pages [@blanchet2024b].\n-   [Codes\n    Dictionary](https://wid.world/codes-dictionary/ \"Describes the general structure of the World Inequality Database (WID)\")\n    (Code Book): It describes the general structure of the World\n    Inequality Database (WID). It explains how information is organized\n    within it and how to retrieve and interpret its content. This\n    document is invaluable for getting familiarized with the\n    construction of WID variables and the structure of the database\n    [@worldinequalitylab2024b]. Converting the web page into a PDF\n    results in a document of 18 pages.\n-   [Summary Table](https://wid.world/summary-table/): It summarizes all\n    available WID.world data. The search tool can look for specific\n    countries, variables, or WID.world codes. It has currently 6253 rows\n    and 16 columns. The summary table is an efficient starting point\n    because it allows for a view of available data, which one can then\n    download for more detailed analysis.\n-   [Computer Code](https://github.com/WIDworld/wid-world): On the\n    GitHub platform, you can inspect and fork the repository that\n    contains all the code used to create the entire database from both\n    the researcher's data and official sources. It consists of 98% of\n    STATA code, the rest (only 2%) is written in R. [^1]\n-   **Data**: There are two ways to download data:\n    -   **Direct Download**: The [interactive\n        page](https://wid.world/data/) allows one to select the required\n        data and download it in the format that best suits one's needs.\n    -   **Advanced Interfaces**: For special requirements, one can\n        access the data with\n        [STATA](https://github.com/thomasblanchet/wid-stata-tool) or [R\n        interfaces](https://github.com/thomasblanchet/wid-r-tool). In\n        the case of the R interface, one can download from GitHub the R\n        `{wid}` package [@wid-2].\n:::\n:::\n\n[^1]: This is somewhat disappointing. As I do not know STATA, these code\n    files do not make much sense to me. However, a quick internet search\n    showed that there are some resources to learn how to translate STATA\n    directives into R commands. Two examples: [Making the Transition? A\n    Guide for Switching from Stata to\n    R](https://www.hertiecodingclub.com/learn/rstudio/stata_to_r/) and\n    [STATA to R cheat\n    sheet](https://rstudio.github.io/cheatsheets/stata2r.pdf).\n\nIt is a lot of work to read all the necessary information before\nstarting. Instead of using this (tedious) sequential approach, I will\ntry an interactive procedure, iteratively changing between theory\n(methodological guidelines) and practice (using R to replicate the\nfigure).\n\n### Replicating income distribution\n\n#### Figure to replicate\n\nAs my test bed, I will use Figure 7 of BHE [@piketty2022, pp. 46].\n\n![Figure 7 of <a class='glossary' title='Piketty, T. (2022). A Brief History of Equality (S. Rendall, Trans.). Harvard University Press.'>BHE</a>, taken from the [original source on\nPiketty's\nwebsite](http://piketty.pse.ens.fr/files/equality/).](BHE-Figure-07-Piketty-min.png){#fig-figure7-piketty\nfig-alt=\"alt-text\" fig-align=\"center\"}\n\n#### Interactive Replication\n\nAs a first approach, I will replicate Figure 7 of BHE with the provided\ninteractive tools of the WID. Here is a good [starting point for income\ninequality](https://wid.world/country/france/).\n\n![Choosing France as \"Country\" and using the default values for income\ninequality (top 10% share and bottom 50%\nshare)](BHE-Figure-07-01-min.png){#fig-BHE-07-00 fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-Figure-07\"}\n\nFrom here, I will show screenshots for every step necessary to replicate\nFigure 7 of BHE, but here in this post, it is @fig-figure7-piketty. If\nyou click on one of the small images below, it will open the figure in\nthe bigger original size, and you can navigate back and forth between\nthe figures in the table below.\n\n::: grid\n::: g-col-4\n##### Figures 3-6\n\n![Choosing France as \"Country\" and using the default values for income\ninequality (top 10% share and bottom 50%\nshare).](BHE-Figure-07-01-min.png){#fig-BHE-07-01 fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-Figure-07\"}\n\n------------------------------------------------------------------------\n\n![Enlarge the time span of the data from 1947 to 1820 with the bottom\nslider.<br/>  ](BHE-Figure-07-02-min.png){#fig-BHE-07-02\nfig-alt=\"alt-text\" fig-align=\"center\" width=\"100%\"\ngroup=\"BHE-Figure-07\"}\n\n------------------------------------------------------------------------\n\n![Hiding the extrapolations (dotted lines) by choosing 'More option' on\nthe top right corner and turning on the radio\nbutton.](BHE-Figure-07-03-min.png){#fig-BHE-07-03 fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-Figure-07\"}\n\n------------------------------------------------------------------------\n\n![Check if 'smooth lines' is active. It should be turned on because it\nis the default value. <br> ](BHE-Figure-07-04-min.png){#fig-BHE-07-04\nfig-alt=\"alt-text\" fig-align=\"center\" width=\"100%\"}\n:::\n\n::: g-col-4\n##### Figures 7-10\n\n![Change the limits of the Y-axis from 0 to 60%. This is different than\nin the original. See my comments later in this\narticle.](BHE-Figure-07-05-min.png){#fig-BHE-07-05 fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-Figure-07\"}\n\n------------------------------------------------------------------------\n\n![Compared with the original, we still will need a third time series for\nthe share of the middle 40% of the\npopulation.](BHE-Figure-07-06-min.png){#fig-BHE-07-06 fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-Figure-07\"}\n\n------------------------------------------------------------------------\n\n![Click on the bottom of the left green navigation bar to open 'More\nIndicators' to include custom indicators in the\ngraph.](BHE-Figure-07-08-min.png){#fig-BHE-07-08 fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-Figure-07\"}\n\n------------------------------------------------------------------------\n\n![Choose 'Income Inequality' to get the option to include a\npreconfigured percentile into the\ngraph.](BHE-Figure-07-09-min.png){#fig-BHE-07-09 fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-Figure-07\"}\n:::\n\n::: g-col-4\n##### Figures 11-14\n\n![Scroll down to select the radio box for the 'Middle 40%'\npercentile.<br /> ](BHE-Figure-07-10-min.png){#fig-BHE-07-10\nfig-alt=\"alt-text\" fig-align=\"center\" width=\"100%\"\ngroup=\"BHE-Figure-07\"}\n\n------------------------------------------------------------------------\n\n![Confirm the default values. I will explain the different options in a\nlater post. <br /> ](BHE-Figure-07-11-min.png){#fig-BHE-07-11\nfig-alt=\"alt-text\" fig-align=\"center\" width=\"100%\"\ngroup=\"BHE-Figure-07\"}\n\n------------------------------------------------------------------------\n\n![Our last action adds the share of the middle 40% to our graph, as was\nseen in @fig-BHE-07-06.\n<br /> ](BHE-Figure-07-12-min.png){#fig-BHE-07-12 fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-Figure-07\"}\n\n------------------------------------------------------------------------\n\n![Hovering with the mouse over the graphs of the interactive website, we\ncan get tooltips with the values for every\nyear.](BHE-Figure-07-13-min.png){#fig-BHE-07-13 fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-Figure-07\"}\n:::\n:::\n\n#### Differences between original and replication\n\nIf we compare both figures side by side, we will see a significant\ndifference. Our replication differs from the original in the years\nbefore 1900. For instance, in our figure, the people with the top 10% of\nincome share about 60% of the total income, in contrast to the 50% share\nin the original graph. I need to find out where these differences come\nfrom. There may have been a correction of the computed extrapolations in\nan update after the book publication. In any case, this difference is\nnot essential here. Remember, the primary purpose of the exercise is to\nunderstand the patterns of the database structure --- and not (at least\nat the moment) to get correct figures.\n\n::: grid\n::: g-col-6\n![Figure 7 of <a class='glossary' title='Piketty, T. (2022). A Brief History of Equality (S. Rendall, Trans.). Harvard University Press.'>BHE</a>, taken from the [original source on\nPiketty's website](http://piketty.pse.ens.fr/files/equality/). The\nshares for the top 10% are lower. It is slightly above 50% of the total\nincome, whereas it is about 60% in the replication. On the other hand,\nthe share of the middle is 40% lower than that of the\nreplication.](BHE-Figure-07-Piketty-min.png){#fig-figure7-piketty-2\nfig-align=\"center\" width=\"95%\" group=\"BHE-figure-compare\"}\n:::\n\n::: g-col-6\n![The result of my replication is showing higher shares for the top 10%\nand accordingly lower shares for the middle 40% in contrast to the\noriginal figure. However, the level of the share of the bottom 50% of\nthe population is approximately the same in both\nfigures.](BHE-Figure-07-13-min.png){#fig-BHE-07-13-2 fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-figure-compare\"}\n:::\n:::\n\nThere are other differences between the two pictures, but they are more\nof cosmetically nature:\n\n-   The choice of colors for the various time series is different.\n-   The labels of the X- and Y-axes are different. The original is\n    labeled every 20 years and contains a vertical line every 10 years,\n    whereas the interactive replication has a 25-year grid. The Y-axis\n    in the replication is missing the %-sign.\n-   In the original, the time-series have different symbols in the data\n    points (circle, triangle), which is vital in black & white (book)\n    publications.\n-   The legend is in the original at a prominent place in the middle of\n    the graph, whereas it is in the interactive replication at the\n    bottom.\n\n### Display the results\n\nUntil now, I have used manually taken screenshots. But there are also\nseveral possibilities to display results offered by the\n<a class='glossary' title='The ‘World Inequality Database’ (WID) aims to provide open and convenient access to the most extensive available database on the historical evolution of the world distribution of income and wealth, both within countries and between countries. WID.WORLD'>WID</a>.\n\n#### Download a JPG-file\n\n![Income inequality, France, 1820-2022 download as JPG from the\n<a class='glossary' title='The ‘World Inequality Database’ (WID) aims to provide open and convenient access to the most extensive available database on the historical evolution of the world distribution of income and wealth, both within countries and between countries. WID.WORLD'>WID</a> site and integrated into the Quarto\ntext.](BHE-Figure-07-graph_dl.jpg){#fig-wid-jpg-figure07\nfig-alt=\"alt-text\" fig-align=\"center\" width=\"100%\"}\n\nNote that there are now fewer labels on the X- and Y-axis. The legend's\nappearance has changed somewhat, and some information that is irrelevant\nin a static view is removed.\n\n#### Copy the URL\n\nAnother option is to copy the URL and integrate it as a link into the\nQuarto text. It opens up a web page with the figure and all the WID\nmenus in your default browser. Others can explore the interactive graph\nor create their own figure from here.\n\nSee the example: [Income inequality, France,\n1820-2022](https://wid.world/share/#0/countrytimeseries/sptinc_p90p100_z;sptinc_p0p50_z;sptinc_p50p90_z/FR/2015/eu/k/p/yearly/s/false/-10/62/curve/true/1820/2022)\n\n#### Embed as iframe\n\nAnother possibility is to embed the graph into an\n<a class='glossary' title='iframes allow you to embed HTML documents inside another HTML document. They offer a seamless way to integrate content from one source into another, enabling developers to create more dynamic and interactive web pages. (dev.to)'>iframe</a>.\n\n<iframe width=\"800\" height=\"400\" src=\"https://wid.world/share/#1/countrytimeseries/sptinc_p90p100_z;sptinc_p0p50_z;sptinc_p50p90_z/FR/2015/eu/k/p/yearly/s/true/9.4765/70/curve/true/1820/2022\">\n\n</iframe>\n\n::: {#cau-wid-iframe-overlapping-legend .callout-caution style=\"color: darkgoldenrod;\"}\n##### Embedding WID iframes has some drawbacks\n\nThe legend overlaps the lower part of the graph. You have either to plan\nduring the construction of the graph to prevent this drawback or\n(better) to adapt the code in the URL itself.\n\nBesides, there is also an annoying cookies-consent message where the\nlink to 'learn more' is wrong by pointing to another graph and not to\nthe cookies policy.\n:::\n\nThe code in the above iframe is:\n\n```         \n<iframe width=\"800\" height=\"400\" src=\"https://wid.world/share/#1/countrytimeseries/sptinc_p90p100_z;sptinc_p0p50_z;sptinc_p50p90_z/FR/2015/eu/k/p/yearly/s/true/9.4765/70/curve/true/1820/2022\"></iframe>\n```\n\nIt turned out that besides changing the delimiter for the axis from\n`/9.4765/70/` to `/0/62/` it is also necessary to enlarge the iframe's\nheight to position the legend lower. With trial & error experimenting, I\ngot a good result after changing the height from `400` to `500`. Here is\nthe adapted iframe where you can see the full figure and also the slider\nto change the time period of the data:\n\n<iframe width=\"800\" height=\"500\" src=\"https://wid.world/share/#1/countrytimeseries/sptinc_p90p100_z;sptinc_p0p50_z;sptinc_p50p90_z/FR/2015/eu/k/p/yearly/s/true/0/62/curve/true/1820/2022\">\n\n</iframe>\n\n## Getting codes for indicators\n\nBy far, the most important result of our replication is that the URL\ncontains the code for used indicators, areas, and percentiles.\n\n```         \nhttps://wid.world/share/#1/countrytimeseries/sptinc_p90p100_z;sptinc_p0p50_z;sptinc_p50p90_z/FR/2015/eu/k/p/yearly/s/false/9.4765/70/curve/true/1820/2022\n```\n\nThis is very helpful because it is now much easier to find the code\nexplication in the [Code\nDictionary](https://wid.world/codes-dictionary/) or the [Summary\nTable](https://wid.world/summary-table/). Let's analyze the example of\nthe `sptinc_p90p100_z` code:\n\n-   **s**: The first letter `s` determines the code series. `s` means\n    \"share\" and contains a fraction between 0 and 1.\n-   **ptinc**: The next five letters are the code for the series\n    concept. This is an essential help because a massive amount of\n    five-letter codes exist. More than half of the 38 pages of the PDF\n    version of the code dictionary lists five-letter codes and their\n    meaning! Searching `ptinc` in the online Code Dictionary with the\n    browser search tool results in \"pretax national income\".\n-   **p90p100**: This one is easy. `p90p100` is the top 10%, the\n    <a class='glossary' title='The set of divisions that produce exactly 100 equal parts in a series of continuous values, such as blood pressure, weight, height, etc. Thus a person with blood pressure above the 80th percentile has a greater blood pressure value than over 80% of the other recorded values.” (CDS, p.323)'>percentiles</a> characterizing people with\n    an income equal to or higher than 90% of the population. Or\n    **p0p50** is the bottom 50% etc.\n\nAdditionally, we have the information from the legend that the units are\nadults, and the income is split equally between couples or other adult\nmembers (= 20 years or older) of the household. Therefore, we can add:\n\n-   **992**: The age code description has three numbers. `992` stands\n    for a population of individuals over age 20.\n-   **j**: The last letter is the unit description. `j` means\n    equal-split adults.\n\nWith these data, we can now look for the corresponding codes in the\ndatabase and filter the database to get only the required information.\nThe variable name is, in our case:\n\n$$\n\\begin{align*}\ns + ptinc + 992 + j = sptinc992j\n\\end{align*}\n$$ {#eq-wid-variable-calculation}\n\nIf we look for this complete code in the [Summary\nTable](https://wid.world/summary-table/), we can read in the column\n\"Simple description of the variable\" the following explanation:\n\n> Pre-tax national income is the sum of all pre-tax personal income\n> flows accruing to the owners of the production factors, labor and\n> capital, before taking into account the operation of the tax/transfer\n> system, but after taking into account the operation of pension system.\n> The central difference between personal factor income and pre-tax\n> income is the treatment of pensions, which are counted on a\n> contribution basis by factor income and on a distribution basis by\n> pre-tax income.\n\n::: {#cau-ID .callout-caution style=\"color: darkgoldenrod;\"}\n##### Explaining just the procedure, not the concepts\n\nRemember that I am not discussing the concepts behind the different\nparameter codes. I just want to stress how to find the code for a\nrequired indicator here. Which concepts to apply and what indicator is\nappropriate for a specific research question will be covered in other\narticles.\n:::\n\n## R Code\n\nThere is with {**wid**} a special R package for downloading data\ndirectly from <a class='glossary' title='The ‘World Inequality Database’ (WID) aims to provide open and convenient access to the most extensive available database on the historical evolution of the world distribution of income and wealth, both within countries and between countries. WID.WORLD'>WID</a> [@wid-3]. Read the instructions on the\n[GitHub repo](https://github.com/thomasblanchet/wid-r-tool) to get\ninstall information.\n\nThe R {wid} package should have a vignette with examples of its usage.\nBut unfortunately, all the links to it are broken or not available\nexcept as [`.Rmd` file in the GitHub\nrepository](https://github.com/thomasblanchet/wid-r-tool/blob/master/vignettes/wid-demo.Rmd)\nitself. I have downloaded and rendered the vignette as a PDF for your\nconvenience.\n\n::: cell\n\n\n```{=html}\n<style type= \"text/css\">\n.column {\ntext-align: center;\n}\n</style>\n```\n\n\n:::\n\n::: columns\n::: {.column width=\"100%\"}\n\n\n{{< downloadthis WID-vignette.pdf label=\"Download WID-vignette as PDF\" dname = \"WID-vignette\" type=success >}}\n\n\n\n:::\n:::\n\n### Plotting data with R\n\nThe central function of the {**wid**} package is `wid::download_wid()`.\nIt has the following parameters:\n\n| Name                  | Type      | Default | Description                                                          |\n|:----------------------|:----------|:--------|:---------------------------------------------------------------------|\n| indicators            | character | all     | Codes corresponding to indicators to retrieve                        |\n| areas                 | character | all     | Areas (mostly countries) for which to retrieve the indicators        |\n| years                 | numeric   | all     | Years for which to retrieve the indicators                           |\n| perc                  | character | all     | <a class='glossary' title='The set of divisions that produce exactly 100 equal parts in a series of continuous values, such as blood pressure, weight, height, etc. Thus a person with blood pressure above the 80th percentile has a greater blood pressure value than over 80% of the other recorded values.” (CDS, p.323)'>Percentiles</a> (part of the distribution) |\n| ages                  | numeric   | all     | Age groups (adults, all ages, elderly, etc.)                         |\n| pop                   | character | all     | Population type (individual, households, tax units, etc.)            |\n| metadata              | logical   | FALSE   | Fetch metadata too? (eg. sources, etc.)                              |\n| verbose               | logical   | FALSE   | Display messages showing progress?                                   |\n| include_extrapolation | logical   | TRUE    | Include data based on extrapolations / interpolations                |\n\n: Description of the arguments for the \\`wid::download_wid()\\` function\n{#tbl-wid-parameters}\n\n#### Download data\n\n::: my-r-code\n::: my-r-code-header\n::: {#cnj-download-wid-data-fr}\n: Download data with `wid::download_wid`\n:::\n:::\n\n::: my-r-code-container\n::: {#lst-download-wid-data-fr}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome_france <- wid::download_wid(\n    indicators = \"sptinc\", # Shares of pre-tax national income\n    areas = \"FR\", # France\n    perc = c(\"p0p50\", \"p50p90\", \"p90p100\"), # Bottom 50%, middle 40% and top 10%\n    ages = 992, # individuals over age 20\n    pop = \"j\" # equal-split adults\n)\n\nsave_data_file(\"WID\", income_france, \"income_france.rds\")\n```\n:::\n\n\n\nDownload data for the shares of France's pre-tax national income.\n:::\n\n(*For this R code chunk, is no output available*)\n:::\n:::\n\n#### Display some random data\n\n::: my-r-code\n::: my-r-code-header\n::: {#cnj-display-some-wid-fr-data}\n: Display some random data imported with `wid::download_wid`\n:::\n:::\n\n::: my-r-code-container\n::: {#lst-display-some-wid-fr-data}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- paste0(here::here(), \"/data/WID/income_france.rds\")\nincome_france <- base::readRDS(data)\nmy_glance_data(income_france, seed = 123)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   obs country   variable percentile year  value\n1    1      FR sptinc992j      p0p50 1820 0.1209\n2   14      FR sptinc992j      p0p50 1923 0.1375\n3  118      FR sptinc992j     p50p90 1910 0.3524\n4  179      FR sptinc992j     p50p90 1975 0.4765\n5  195      FR sptinc992j     p50p90 1991 0.4694\n6  229      FR sptinc992j    p90p100 1880 0.5932\n7  244      FR sptinc992j    p90p100 1927 0.4699\n8  299      FR sptinc992j    p90p100 1982 0.2994\n9  306      FR sptinc992j    p90p100 1989 0.3319\n10 339      FR sptinc992j    p90p100 2022 0.3479\n```\n\n\n:::\n:::\n\n\n\nDisplay some random data imported with `wid::download_wid`, including\nthe first and last row.\n:::\n:::\n:::\n\nInspecting the data, we see:\n\n-   Our dataset has 339 records.\n\n-   All presented records have an area code `FR`, which stands for\n    France.\n\n-   All presented records have the variable name `sptinc992j`. This\n    conforms to our previous calculation.\n\n-   We see three different values for percentiles in the randomly\n    displayed data: `p0p50`, `p50p90`, and `p90p100` representing the\n    income of the bottom 50%, the middle 40%, and the top 10% of the\n    population.\n\n-   Our random data show a period from 1820 to 2022.\n\n-   The quantity for each record contains the column `value`.\n\nOverall, The result looks nice, but we must check the data more\nthoroughly. Is there really only one type of variable? [^2]\n\n[^2]: How important this check is showed me a previous version in which\n    I had not included `ages = 992` because I thought the adult\n    population was already defined with `pop = \"j\"`, the letter code for\n    equal-split *adults*. But it turned out that without the explicit\n    definition for the age, I also downloaded the default value `999`\n    (all ages).\n\n#### Display data structure\n\n::: my-r-code\n::: my-r-code-header\n::: {#cnj-wid-fr-income-data-structure}\n: Data structure for the France data for pre-tax income (1820-2022)\n:::\n:::\n\n::: my-r-code-container\n::: {#lst-wid-fr-income-data-structureD}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskimr::skim(income_france)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |              |\n|:------------------------|:-------------|\n|Name                     |income_france |\n|Number of rows           |339           |\n|Number of columns        |5             |\n|_______________________  |              |\n|Column type frequency:   |              |\n|character                |3             |\n|numeric                  |2             |\n|________________________ |              |\n|Group variables          |None          |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|country       |         0|             1|   2|   2|     0|        1|          0|\n|variable      |         0|             1|  10|  10|     0|        1|          0|\n|percentile    |         0|             1|   5|   7|     0|        3|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    mean|    sd|      p0|     p25|     p50|     p75|    p100|hist  |\n|:-------------|---------:|-------------:|-------:|-----:|-------:|-------:|-------:|-------:|-------:|:-----|\n|year          |         0|             1| 1964.23| 37.08| 1820.00| 1938.00| 1966.00| 1994.00| 2022.00|▁▁▆▇▇ |\n|value         |         0|             1|    0.33|  0.12|    0.12|    0.21|    0.34|    0.45|    0.61|▇▂▇▇▁ |\n\n\n:::\n:::\n\n\n\nUsing the {**skimr**} package to display the data structure for the\nFrance pre-tax income data 1820-2022\n:::\n:::\n:::\n\nHere, we see that no data are missing, that we have only one value for\nthe variables `country` and `variable`, and exactly the required three\nvalues for `percentile`.\n\nWe also see from the small histogram for `year` that we do not have many\ndata points for more of the first half of the time.\n\n#### Display the national income figure\n\n::: my-r-code\n::: my-r-code-header\n::: {#cnj-display-graph-income-france}\n: Pre-tax national income inequality in France, 1820-2022\n:::\n:::\n\n::: my-r-code-container\n::: {#lst-display-graph-income-france}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot2::ggplot(income_france, \n    ggplot2::aes(x = year, y = value, color = percentile)) +\n    ggplot2::geom_line() + \n    ggplot2::geom_point() +\n    # ggplot2::geom_smooth(span = .9) + # for smoothing\n    ggplot2::ylab(\"share of income\") +\n    ggplot2::scale_color_discrete(\n        labels = c(\"p0p50\" = \"bottom 50%\", \"p90p100\" = \"top 10%\", \"p50p90\" = \"middle 40%\")\n    ) + \n    ggplot2::ggtitle(\"Pre-tax national income inequality in France, 1820-2022\") +\n    ggplot2::theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/display-graph-income-france-1.png){width=672}\n:::\n\n```{.r .cell-code}\n## save plot just once\n# ggplot2::ggsave(filename = \"BHE-sptinc992j_fr.png\")\n```\n:::\n\n\n\nPre-tax national income inequality in France, 1820-2022\n:::\n:::\n:::\n\n## Comparison of my result with the original Figure 7\n\n::: grid\n::: g-col-6\n![Figure 7 of <a class='glossary' title='Piketty, T. (2022). A Brief History of Equality (S. Rendall, Trans.). Harvard University Press.'>BHE</a>, taken from the [original source on\nPiketty's\nwebsite](http://piketty.pse.ens.fr/files/equality/).](BHE-Figure-07-Piketty-min.png){#fig-figure7-piketty-3\nfig-align=\"center\" group=\"BHE-figure-compare2\"}\n:::\n\n::: g-col-6\n![Resulting figure after data download and plotting with\nR](BHE-sptinc992j_fr-min.png){#fig-BHE-sptinc992j-fr fig-alt=\"alt-text\"\nfig-align=\"center\" width=\"100%\" group=\"BHE-figure-compare2\"}\n:::\n:::\n\nWe are pretty near if we compare the above plots. Besides the mentioned\ndifference in the magnitude of the top 10% and middle 40% before 1900,\nthere are the following differences:\n\n-   title\n-   grid for x- and y-axis\n-   symbols for the data points\n-   position of the legend\n-   text of legend\n-   the smoothness of the time series\n\nHowever, these differences are all solvable with the appropriate R code.\nI leave it here because the purpose of this article was to work with\n<a class='glossary' title='The ‘World Inequality Database’ (WID) aims to provide open and convenient access to the most extensive available database on the historical evolution of the world distribution of income and wealth, both within countries and between countries. WID.WORLD'>WID</a> (and not to replicate figure 7 of\n<a class='glossary' title='Piketty, T. (2022). A Brief History of Equality (S. Rendall, Trans.). Harvard University Press.'>BHE</a> exactly.)\n\n## Conclusion\n\nI have shown procedures for working with the inequality data of\n<a class='glossary' title='The ‘World Inequality Database’ (WID) aims to provide open and convenient access to the most extensive available database on the historical evolution of the world distribution of income and wealth, both within countries and between countries. WID.WORLD'>WID</a>.\n\n-   One approach explores the interactive website on\n    [wid.world](https://wid.world/) and tries to create the desired\n    graph. There are several ways to use the resulting figure:\n    -   Downloading the picture as <a class='glossary' title='JPEG (/ˈdʒeɪpɛɡ/ JAY-peg, short for Joint Photographic Experts Group is a commonly used method of lossy compression for digital images. (Wikipedia)'>JPG</a>\n    -   Embedding a link to the interactive graph on your website\n    -   Embedding the result as <a class='glossary' title='iframes allow you to embed HTML documents inside another HTML document. They offer a seamless way to integrate content from one source into another, enabling developers to create more dynamic and interactive web pages. (dev.to)'>iframe</a> in your website\n    -   Exploring the code in the URL and using it for the second\n        approach (downloading the required data with R)\n-   The second approach uses the {**wid**} R package, especially the\n    function `wid::download_wid()`. Knowing the required codes for the\n    download function is essential. The first approach could help find\n    the correct code composition in the WID code book, the [Codes\n    Dictionary](https://wid.world/codes-dictionary/) or in the [Summary\n    Table](https://wid.world/summary-table/).\n\n::: {#imp-how-to-not-enough .callout-important style=\"color: red;\"}\n##### How-to procedures are not enough\n\nThe post only describes \"how-to\" procedures for WID and does not discuss\nthe available concepts appropriate for specific research questions. I\nplan to describe and reflect on concepts for inequality research in\nlater blog posts.\n:::\n\n## Appendix\n\n###### Glossary\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:left;\"> definition </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Advanced Organizer </td>\n   <td style=\"text-align:left;\"> Advance organizers are pedagogic devices that bridge the gap between what learners already know and what learners need to know. (&lt;a href=\"https://link.springer.com/referenceworkentry/10.1007/978-1-4419-1428-6_157\"&gt;Encyclopedia of the Science of Learning&lt;/a&gt;) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BHE </td>\n   <td style=\"text-align:left;\"> Piketty, T. (2022). A Brief History of Equality (S. Rendall, Trans.). Harvard University Press. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> DINA </td>\n   <td style=\"text-align:left;\"> Distributional national accounts (DINAs) aim to gather information on the distribution of the net national income and to explore it over time. ([Distributional National Accounts (DINA) for Austria, 2004-2016](https://wid.world/document/distributional-national-accounts-dina-for-austria-2004-2016-world-inequality-lab-wp-2020-23/)) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> iframe </td>\n   <td style=\"text-align:left;\"> iframes allow you to embed HTML documents inside another HTML document. They offer a seamless way to integrate content from one source into another, enabling developers to create more dynamic and interactive web pages. ([dev.to](https://dev.to/joanayebola/what-is-iframe-and-how-to-use-them-1c63)) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> JPG </td>\n   <td style=\"text-align:left;\"> JPEG (/ˈdʒeɪpɛɡ/ JAY-peg, short for Joint Photographic Experts Group is a commonly used method of lossy compression for digital images. [(Wikipedia](https://en.wikipedia.org/wiki/JPEG)) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> National Accounts </td>\n   <td style=\"text-align:left;\"> National accounts are a system of accounts and balance sheets that provide a broad and integrated framework to describe an economy, whether a region, a country, or a group of countries such as the European Union (EU). For internationally comparable national accounts this system needs to be based on common concepts, definitions, classifications and accounting rules, in order to arrive at a consistent, reliable and comparable quantitative description of an economy. National accounts provide systematic and detailed economic data useful for economic analysis to support the development and monitoring of policy-making. [eurostat - Statistics explained] </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Percentile </td>\n   <td style=\"text-align:left;\"> The set of divisions that produce exactly 100 equal parts in a series of continuous values, such as blood pressure, weight, height, etc. Thus a person with blood pressure above the 80th percentile has a greater blood pressure value than over 80% of the other recorded values.” (CDS, p.323) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WID </td>\n   <td style=\"text-align:left;\"> The 'World Inequality Database' (WID) aims to provide open and convenient access to the most extensive available database on the historical evolution of the world distribution of income and wealth, both within countries and between countries. [WID.WORLD](https://wid.world/wid-world/) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}