---
title: "Hiding a secret API token"
subtitle: "An article that explains something."
author: "Peter Baumgartner"
date: "2023-05-06"
date-modified: "2023-05-06"
image: ""
categories: [API, httr2]
draft: true
---

I plan to write an R Package. I will call it `hypo2md`, and it should
search and import annotations from
[Hypothes.is](https://web.hypothes.is/ "is a open-source software for web annotations")
into R markdown files. I need this functionality to process my
highlights and comments generated during reading in my note-taking app
[Obsidian](https://obsidian.md/ "Obsidian is a note-taking app"). 

But writing about my package plans is not the goal of this post. Here I
want to describe one of the learnings I had during my first experiments
with the [Hypothes.is
API](https://h.readthedocs.io/en/latest/api-reference/).

Reading the two articles by Hadley Wickham about [httr2 R
package](R%20package) ([get
started](https://httr2.r-lib.org/articles/httr2.html) and [wrapping
APIs](https://httr2.r-lib.org/articles/wrapping-apis.html)), I learned
the basics of how to interface with APIs. As Hypothes.is requires an API
user token, one particular problem I would need to overcome is [secret
management](https://httr2.r-lib.org/articles/wrapping-apis.html#secret-management).

Even after reading the detailed instructions multiple times, the code
described in "Wrapping APIs" didn't work for me. As I finally solved the
problem, I thought my errors could be interesting for other Newbies as
well.

## 5 steps to hide your secrets

I am not going to use executable R program code for the explanation. It
is difficult to show the functionality in a blog post and it may be even
more difficult to prevent misunderstanding as it happened with me, when
I followed the code.

::: callout-note
Note that there are five types of callouts, including: `note`,
`warning`, `important`, `tip`, and `caution`.
:::

::: callout-tip
## Tip with Title

This is an example of a callout with a title.
:::

::: {.callout-caution collapse="true" appearance="default"}
## Expand To Learn About Collapse

This is an example of a 'folded' caution callout that can be expanded by
the user. You can use `collapse="true"` to collapse it by default or
`collapse="false"` to make a collapsible callout that is expanded by
default.
:::

## Some formatting commands

``` {.zsh filename="Terminal"}
quarto create-project myproject
```

+---------------------+-------------------------+------------------+
| \`\`\` {.yaml fil   | \`\`\` {.yaml filen     | \`\`\` {.yaml f  |
| en                  | am                      | i                |
| ame="\_quarto.yml"} | e="dir/\_metadata.yml"} | lename="merged"} |
| format: html: toc:  | format: html:           | format: html:    |
| true                | code-fold: true         | toc: true        |
| bibliography: -     | bibliography: -         |                  |
| refs.bib            | proj.bib                | code-fold: true  |
|                     |                         | bibliography: -  |
| \`\`\`              | \`\`\`                  | refs.bib -       |
|                     |                         | proj.bib \`\`\`  |
+---------------------+-------------------------+------------------+

: {tbl-colwidths="\[33,33,33\]"}

+-------------------------------+------------------------------------+
| ```                           | ``` {.                             |
| {                             | yaml filename="dir/_metadata.yml"} |
| .yaml filename="_quarto.yml"} | format:                            |
| format:                       |   html:                            |
|   html:                       |     code-fold: true                |
|     toc: true                 | bibliography:                      |
| bibliography:                 |   - proj.bib                       |
|   - refs.bib                  | ```                                |
| ```                           |                                    |
+-------------------------------+------------------------------------+

: {tbl-colwidths="\[35,65\]"}

+----------------------------+---------------------------------------+
| This here is a text to     | \` {.yaml                             |
| explain how the program is | filename="dir/\_metadata.yml"}        |
| working. I am using a      | format: html: code-fold: true         |
| table to format the        | bibliography: - proj.bib \`\`\`       |
| different aspect of the    |                                       |
| code.                      |                                       |
|                            |                                       |
| It is possible to write    |                                       |
| text in two separate       |                                       |
| columns. But it seem       |                                       |
| complex to produce the     |                                       |
| table. Maybe one could use |                                       |
| a table generator?         |                                       |
+----------------------------+---------------------------------------+

: {tbl-colwidths="\[65,35\]"}

| Default                           | Left | Right | Center |
|-----------------------------------|:-----|------:|:------:|
| It is possible to write text in   | 12   |    12 |   12   |
| two separate columns. But it seem | 123  |   123 |  123   |
| complex to produce the table.     | 1    |     1 |   1    |

: Demonstration of PIP Table Syntax

## Table generated from Tables Generator

+------+------+------+------+------+------+------+------+------+
| O    | So   | Note | Cat  | Su   | E    | Code | T    |      |
| r    | urce | type | e    | b    | moji |      | itle |      |
| igin |      | ===  | gory | ject |      | ===  |      |      |
| ===  | ==== | ==== | ===  | ===  | ===  | ==== | ===  |      |
| ==== | ==== |      | ==== | ==== | ==== | 0w   | ==== |      |
| Cli  | we   |      |      |      | 🌐   |      |      |      |
| p    | b-cl |      |      |      |      |      |      |      |
| ping | ip   |      |      |      |      |      |      |      |
| N    | ping |      |      |      |      |      |      |      |
| otes |      |      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+------+
|      |      |      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+------+
| E    | ???  | ???  |      |      | 📬   | 0e   |      |      |
| m    |      |      |      |      |      |      |      |      |
| ails |      |      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+------+
| Per  | a    | per  |      |      | 🙋🏻‍♂️   |      |      |      |
| s    | pi-a | s    |      |      | \|   |      |      |      |
| onal | rt   | onal |      |      | 0pi  |      |      |      |
|      | icle |      |      |      | \|   |      |      |      |
|      | pb   |      |      |      | PI   |      |      |      |
|      |      |      |      |      | \|   |      |      |      |
|      |      |      |      |      | \|   |      |      |      |
|      |      |      |      |      | \|   |      |      |      |
|      |      |      |      |      | \|   |      |      |      |
|      |      |      |      |      | \|   |      |      |      |
|      |      |      |      |      | \|   |      |      |      |
+------+------+------+------+------+------+------+------+------+
| Pr   | scan | pr   | fi   |      | 🆔   | 0id  | FI   |      |
| i    | up   | i    | n    |      |      |      | GH   |      |
| vate | hold | vate | ance |      |      |      |      |      |
|      | ge   |      | h    |      |      |      |      |      |
|      | orge |      | e    |      |      |      |      |      |
|      | jo   |      | alth |      |      |      |      |      |
|      | plin |      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+------+
| Rea  | re   |      | art  |      | 📄   | 0a   | FNA  |      |
| d    | ader |      | i    |      |      |      | LNA  |      |
| wise | a    |      | cles |      |      |      |      |      |
| Ar   | pi-a |      |      |      |      |      |      |      |
| t    | rt   |      |      |      |      |      |      |      |
| icle | icle |      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+------+
| Rea  | re   |      | b    |      | 📖   | 0b   | FNB  |      |
| d    | ad   |      | ooks |      |      |      | LNB  |      |
| wise | wise |      |      |      |      |      |      |      |
| Book |      |      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+------+
| Rea  |      |      |      |      | 🔉   | 0po  | FNP  |      |
| d    |      |      |      |      |      |      |      |      |
| wise |      |      |      |      |      |      |      |      |
| Pod  |      |      |      |      |      |      |      |      |
| c    |      |      |      |      |      |      |      |      |
| asts |      |      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+------+
| Rea  | t    |      | t    |      | 🐥   | 0t   |      |      |
| d    | wi   |      | w    |      |      |      |      |      |
| wise | tter |      | eets |      |      |      |      |      |
| Tw   |      |      |      |      |      |      |      |      |
| i    |      |      |      |      |      |      |      |      |
| tter |      |      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+------+
| Z    |      |      | misc |      |      |      |      |      |
| e    |      |      |      |      |      |      |      |      |
| ttel |      |      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+------+
|      |      |      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+------+

## Table with RStudio Visual Editor

| Col1                                   | Col2     | Col3     |
|----------------------------------------|----------|----------|
| Here I got the first row               | sadfsadf | sdafasdf |
| How about two or more lines in one row | asdfasdf | asdfasdf |
| Last row                               | asdfsadf | sdfasdf  |

: This is a test table

+---------------------------------:+:----------------------------------+
| ![Click on the circle symbol at  | ![Choose from the drop-down menu  |
| the top right                    | the option "Refresh               |
| corner](/p                       | Now"](/                           |
| osts/2023-05-05-how-to-delete-gi | posts/2023-05-05-how-to-delete-gi |
| t-branches/images/rstudio-refres | t-branches/images/rstudio-refresh |
| h-branch-listing-circle-min.png) | -branch-listing-manually-min.png) |
+----------------------------------+-----------------------------------+

::: {layout="[[1,1],[1,1]]"}
![Click on the circle symbol at the top right
corner](/posts/2023-05-05-how-to-delete-git-branches/images/rstudio-refresh-branch-listing-circle-min.png){fig-align="center"}

![Choose from the drop-down menu the option "Refresh
Now"](/posts/2023-05-05-how-to-delete-git-branches/images/rstudio-refresh-branch-listing-manually-min.png){fig-align="center"}
:::

## Figure divs

::: {#fig-elephant}
<iframe width="560" height="315" src="https://www.youtube.com/embed/SNggmeilXDQ">

</iframe>

Elephant
:::

## Using figure divs for text

::: {layout-nrow="2"}
**This is the left column.**

**This is the right column.**

I am not going to use executable R program code for the explanation. It
is difficult to show the functionality in a blog post and it may be even
more difficult to prevent misunderstanding as it happened with me, when
I followed the code.

I am not going to use executable R program code for the explanation. It
is difficult to show the functionality in a blog post and it may be even
more difficult to prevent misunderstanding as it happened with me, when
I followed the code.
:::

## Two columns Layout in Quarto

::: grid
::: g-col-6
## First column

I would like to have text here

Sentence becomes longer, it should automatically stay in their column
:::

::: g-col-6
## Second column

and here

More text
:::
:::

## Two columns Layout in Quarto with `layout-nrow=4` (pb)

::: {layout-nrow="4"}
Zeile 1a

Zeile 1b

Zeile 2a

Zeile 2b

Zeile 3a

Zeile 3b

Zeile 4a

Zeile 4b
:::

## Two columns Layout in Quarto with `layout-ncol=2` (pb)

::: {layout-ncol="2"}
Zeile 1a

Zeile 1b

Zeile 2a

Zeile 2b

Zeile 3a

Zeile 3b

Zeile 4a

Zeile 4b
:::

## Two columns Layout in Quarto (Stackoverflow)

::: {layout-ncol="2"}
**First column**

**Second column**

I would like to have text here

and here

Sentence becomes longer, it should automatically stay in their column

More text
:::

## Two columns Layout in Quarto (Variant 2)

::: {layout="[[10,10], [40,40], [25,25], [1,1]]"}
**First column**

**Second column**

I would like to have text here

and here

Sentence becomes longer, it should automatically stay in their column

More text
:::

## Two columns Layout in Quarto (Version 1)

::: {layout-ncol="2"}
**First column**

**Second column**

I would like to have text here

and here

Sentence becomes longer, it should automatically stay in their column

More text
:::

## Two columns Layout in Quarto (Version 2)

::: {layout="[[10,5], [40,20], [26,13], [2,1]]"}
**First column**

**Second column**

I would like to have text here

and here

Sentence becomes longer, it should automatically stay in their column

More text
:::

***

------------------------


